2022-05-25 03:08:06 align.main INFO : Reading netlist: /home/elonjia/Desktop/tool_package/ALIGN-pdk-sky130/examples/DCDC_DAC/DCDC_DAC.sp subckt=DCDC_DAC, flat=1
2022-05-25 03:08:06 align.compiler.compiler INFO : Starting topology identification...
2022-05-25 03:08:06 align.cmdline ERROR : Fatal Error. Cannot proceed
Traceback (most recent call last):
  File "/home/elonjia/Desktop/tool_package/ALIGN-public/general/lib/python3.8/site-packages/align/cmdline.py", line 166, in parse_args
    return schematic2layout(**vars(arguments))
  File "/home/elonjia/Desktop/tool_package/ALIGN-public/general/lib/python3.8/site-packages/align/main.py", line 163, in schematic2layout
    primitive_lib = generate_hierarchy(netlist, subckt, topology_dir, flatten, pdk_dir)
  File "/home/elonjia/Desktop/tool_package/ALIGN-public/general/lib/python3.8/site-packages/align/compiler/compiler.py", line 27, in generate_hierarchy
    ckt_data, primitive_library = compiler_input(
  File "/home/elonjia/Desktop/tool_package/ALIGN-public/general/lib/python3.8/site-packages/align/compiler/compiler.py", line 81, in compiler_input
    ckt_parser.parse(lines)
  File "/home/elonjia/Desktop/tool_package/ALIGN-public/general/lib/python3.8/site-packages/align/schema/parser.py", line 88, in parse
    self._dispatch(cache)
  File "/home/elonjia/Desktop/tool_package/ALIGN-public/general/lib/python3.8/site-packages/align/schema/parser.py", line 106, in _dispatch
    self._process_instance(token.value.upper(), args, kwargs)
  File "/home/elonjia/Desktop/tool_package/ALIGN-public/general/lib/python3.8/site-packages/align/schema/parser.py", line 161, in _process_instance
    assert len(args) == len(model.pins), \
AssertionError: Model SKY130_FD_PR__NFET_01V8 has 4 pins ['D', 'G', 'S', 'B']. 8 nets ['V0', 'VOUT', 'SKY130_FD_PR__CAP_MIM_M3_1', 'M2', 'V1', 'D1', 'VGND', 'VGND'] were passed when instantiating M20.
